//! cosmic-connect-core
//!
//! KDE Connect protocol implementation in Rust.
//! Shared library for COSMIC Connect Android and COSMIC Desktop.
//!
//! ## Architecture
//!
//! This library provides a complete implementation of the KDE Connect protocol v7,
//! designed for cross-platform use via FFI (Foreign Function Interface).
//!
//! ### Modules
//!
//! - `protocol`: Core protocol types (NetworkPacket, Device, Identity)
//! - `network`: Network layer (Discovery, TCP transport)
//! - `crypto`: Cryptography (TLS, Certificate management)
//! - `plugins`: Plugin system and implementations
//! - `ffi`: Foreign Function Interface for Kotlin/Swift
//!
//! ## Example
//!
//! ```rust
//! use cosmic_connect_core::Packet;
//! use serde_json::json;
//!
//! // Create a packet
//! let packet = Packet::new("kdeconnect.ping", json!({}));
//!
//! // Serialize with newline terminator (KDE Connect protocol requirement)
//! let bytes = packet.to_bytes().unwrap();
//! assert_eq!(bytes.last(), Some(&b'\n'));
//! ```

// Re-export commonly used types
pub use error::{ProtocolError, Result};
pub use protocol::Packet;

// Re-export modules for convenience
pub use network::discovery;

// Re-export FFI types for UniFFI scaffolding
pub use ffi::{
    FfiPacket, FfiDeviceInfo, FfiCertificate, FfiBatteryState,
    FfiCapabilities, FfiPingStats, DiscoveryEvent,
    DiscoveryCallback, PluginCallback,
    DiscoveryService, PluginManager,
    initialize, get_version, get_protocol_version,
    create_packet, create_packet_with_id, serialize_packet, deserialize_packet,
    generate_certificate, load_certificate, save_certificate, get_certificate_fingerprint,
    start_discovery, create_plugin_manager,
};

// Public modules
pub mod protocol;
pub mod network;
pub mod crypto;
pub mod plugins;
pub mod error;

// FFI module (for Android/iOS bindings) - always enabled
pub mod ffi;

// Include UniFFI scaffolding generated by build.rs
uniffi::include_scaffolding!("cosmic_connect_core");

// Version information
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
pub const PROTOCOL_VERSION: i32 = 7;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_version() {
        assert!(!VERSION.is_empty());
    }

    #[test]
    fn test_protocol_version() {
        assert_eq!(PROTOCOL_VERSION, 7);
    }
}
