//! cosmic-connect-core
//!
//! COSMIC Connect protocol implementation in Rust.
//! Shared library for COSMIC Connect Android and COSMIC Desktop.
//!
//! ## Architecture
//!
//! This library provides a complete implementation of the KDE Connect-compatible protocol v7,
//! designed for cross-platform use via FFI (Foreign Function Interface).
//!
//! ### Modules
//!
//! - `protocol`: Core protocol types (NetworkPacket, Device, Identity)
//! - `network`: Network layer (Discovery, TCP transport)
//! - `crypto`: Cryptography (TLS, Certificate management)
//! - `plugins`: Plugin system and implementations
//! - `ffi`: Foreign Function Interface for Kotlin/Swift
//!
//! ## Example
//!
//! ```rust
//! use cosmic_connect_core::Packet;
//! use serde_json::json;
//!
//! // Create a packet
//! let packet = Packet::new("cconnect.ping", json!({}));
//!
//! // Serialize with newline terminator (COSMIC Connect protocol requirement)
//! let bytes = packet.to_bytes().unwrap();
//! assert_eq!(bytes.last(), Some(&b'\n'));
//! ```

// Re-export commonly used types
pub use error::{ProtocolError, Result};
pub use protocol::Packet;

// Re-export modules for convenience
pub use network::discovery;
pub use network::transport;

// Re-export FFI types for UniFFI scaffolding
pub use ffi::{
    FfiPacket, FfiDeviceInfo, FfiCertificate, FfiBatteryState,
    FfiCapabilities, FfiPingStats, DiscoveryEvent,
    DiscoveryCallback, PluginCallback, PayloadCallback,
    DiscoveryService, PluginManager, PayloadTransferHandle,
    initialize, get_version, get_protocol_version,
    create_packet, create_packet_with_id, serialize_packet, deserialize_packet,
    generate_certificate, load_certificate, save_certificate, get_certificate_fingerprint,
    start_discovery, create_plugin_manager,
    create_file_share_packet, create_text_share_packet, create_url_share_packet,
    create_multifile_update_packet, start_payload_download,
    create_clipboard_packet, create_clipboard_connect_packet,
    create_findmyphone_request,
    create_runcommand_request_list, create_runcommand_execute, create_runcommand_setup,
    create_telephony_event, create_mute_request, create_sms_messages,
    create_conversations_request, create_conversation_request,
    create_attachment_request, create_send_sms_request,
    create_battery_packet, create_battery_request,
    create_open_url_packet, create_open_file_packet, create_open_text_packet,
    create_open_response_packet, create_open_capability_packet,
    create_notification_packet, create_cancel_notification_packet,
    create_notification_request_packet, create_dismiss_notification_packet,
    create_notification_action_packet, create_notification_reply_packet,
    create_rich_notification_packet, attach_image_to_notification_packet,
    create_notification_image, notification_image_from_bytes,
    scale_notification_image, get_notification_image_data,
    create_presenter_pointer, create_presenter_stop,
    create_systemvolume_volume, create_systemvolume_mute,
    create_systemvolume_enable, create_systemvolume_request_sinks,
    create_connectivity_report,
    create_contacts_response_uids, create_contacts_response_vcards,
    create_mpris_request,
    create_mousepad_request, create_mousepad_echo, create_mousepad_keyboardstate,
    create_digitizer_session, create_digitizer_event,
    create_sftp_packet,
    create_lock_packet, create_lock_request, create_lock_status_request,
    create_webcam_start_request, create_webcam_stop_request, create_webcam_capability_request,
    create_webcam_status, create_webcam_capability,
};

// Re-export NotificationImage for UniFFI
pub use plugins::notification_image::NotificationImage;

// Public modules
pub mod protocol;
pub mod network;
pub mod crypto;
pub mod plugins;
pub mod error;

// FFI module (for Android/iOS bindings) - always enabled
pub mod ffi;

// Video/V4L2 module (Linux only, feature-gated)
#[cfg(feature = "video")]
pub mod video;

// Include UniFFI scaffolding generated by build.rs
uniffi::include_scaffolding!("cosmic_connect_core");

// Version information
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
/// Protocol version 8 (KDE Connect compatible)
pub const PROTOCOL_VERSION: i32 = 8;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_version() {
        assert!(!VERSION.is_empty());
    }

    #[test]
    fn test_protocol_version() {
        assert_eq!(PROTOCOL_VERSION, 8);
    }
}
